### ISSUE TITLE
使用C++ 运行 detect tensorrt 模型识别速度反而比以前更慢了

### ISSUE THREAD

**Issue by shu681** [emptysoal/TensorRT-YOLOv8#5]
你好大佬，非常牛的项目，解决了我老大难问题，现在情况是这样的：
我用的是C++/detect/main.cpp这块代码，正常编译打包，我用的是我自己训练的模型，engine文件我已经通过trtexec生成了，命令是
```
/usr/src/tensorrt/bin/trtexec --onnx=detect-1031.onnx --saveEngine=detect-1031.int8.engine --device=0 --optShapes=images:1x3x1280x1280 --int8 --workspace=1024 --buildOnly --memPoolSize=workspace:256
```

我用python测试engine的每帧图片（1920*1080）识别大约耗时100ms，但是我使用咱们这个系统的代码，测试每帧耗时稳定在222-226ms，通过jtop能看到占用显存，不知道为什么会比python识别时间更长。

不知道我是哪里出了问题，请大佬解惑，十分感谢

平台信息：
> Jetson Orin Nano 4G
> Jetpack 5.1.1

**Comment by emptysoal** [comment]
这个我也不清楚，我只在服务器上运行过，不好意思

**Comment by shu681** [comment]
好吧，谢谢大佬关注
